[package]
name = "byte_input_conversion"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-core = { git = "https://github.com/hotg-ai/rune", tag = "nightly" }
hotg-rune-proc-blocks = { git = "https://github.com/hotg-ai/rune", tag = "nightly" }
log = { version = "0.4", default-features = false }
serde = { version = "1", default-features = false }
# serde_json = "1"
serde-json-core = "0.4.0"