[package]
name = "input_type_conversion"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-core = { git = "https://github.com/hotg-ai/rune", rev = "0ffa7738c30c0a33b06d405c8301ae1905d7e2eb" }
hotg-rune-proc-blocks = { git = "https://github.com/hotg-ai/rune", rev = "0ffa7738c30c0a33b06d405c8301ae1905d7e2eb" }
# tokenizers = "0.11.0"
# openssl = { version = "0.10", features = ["vendored"] }
log = { version = "0.4", default-features = false }
# no-std-compat = "0.4.1"