version: 1
image: runicos/base

pipeline:
  segment_input:
    capability: RAW
    outputs:
      - type: u8
        dimensions: [1, 382]
  mask_input:
    capability: RAW
    outputs:
      - type: u8
        dimensions: [1, 382]
  token_ids_input:
    capability: RAW
    outputs:
      - type: u8
        dimensions: [1, 382]
  segment_cast:
    proc-block: './byte_input_conversion'
    inputs:
      - segment_input
    outputs:
      - type: i32
        dimensions: [1, 382]
  mask_cast:
    proc-block: './byte_input_conversion'
    inputs:
      - mask_input
    outputs:
      - type: i32
        dimensions: [1, 382]
  token_ids_cast:
    proc-block: './byte_input_conversion'
    inputs:
      - token_ids_input
    outputs:
      - type: i32
        dimensions: [1, 382]
  classify:
    model: './bert.tflite'
    inputs:
      # - extract_tokens.0
      # - extract_tokens.1
      # - extract_tokens.2
      - segment_cast
      - mask_cast
      - token_ids_cast
    outputs:
      - type: f32
        dimensions: [1, 382]
      - type: f32
        dimensions: [1, 382]
  serial:
    out: serial
    inputs:
      - classify.0
      - classify.1
